apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform
  labels:
    {{- include "platform.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2m
    nginx.ingress.kubernetes.io/limit-rps: "20"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.host }}
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend: { service: { name: auth-service, port: { number: 8000 } } }
          - path: /api/network
            pathType: Prefix
            backend: { service: { name: network-service, port: { number: 8000 } } }
          - path: /api/aws
            pathType: Prefix
            backend: { service: { name: aws-service, port: { number: 8000 } } }
          - path: /
            pathType: Prefix
            backend: { service: { name: frontend-service, port: { number: 8080 } } }
