apiVersion: v1
kind: Secret
metadata:
  name: platform-development-secrets
  labels:
    {{- include "platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-mysql-password: {{ .Values.developmentSecrets.authDatabasePassword | quote }}
  network-mysql-password: {{ .Values.developmentSecrets.networkDatabasePassword | quote }}
  aws-mysql-password: {{ .Values.developmentSecrets.awsDatabasePassword | quote }}
  auth-mysql-root-password: {{ .Values.developmentSecrets.authDatabaseRootPassword | quote }}
  network-mysql-root-password: {{ .Values.developmentSecrets.networkDatabaseRootPassword | quote }}
  aws-mysql-root-password: {{ .Values.developmentSecrets.awsDatabaseRootPassword | quote }}
  auth-django-secret: {{ .Values.developmentSecrets.authDjangoSecret | quote }}
  network-django-secret: {{ .Values.developmentSecrets.networkDjangoSecret | quote }}
  aws-django-secret: {{ .Values.developmentSecrets.awsDjangoSecret | quote }}
