apiVersion: v1
kind: Secret
metadata:
  name: platform-development-secrets
  labels:
    {{- include "platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-postgres-password: {{ .Values.developmentSecrets.authDatabasePassword | quote }}
  network-postgres-password: {{ .Values.developmentSecrets.networkDatabasePassword | quote }}
  aws-postgres-password: {{ .Values.developmentSecrets.awsDatabasePassword | quote }}
  auth-django-secret: {{ .Values.developmentSecrets.authDjangoSecret | quote }}
  network-django-secret: {{ .Values.developmentSecrets.networkDjangoSecret | quote }}
  aws-django-secret: {{ .Values.developmentSecrets.awsDjangoSecret | quote }}

